# Generated by Django 2.2 on 2019-04-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoN',
            fields=[
                ('w1_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('w2_id', models.PositiveIntegerField()),
                ('freq', models.PositiveIntegerField(blank=True, null=True)),
                ('sig', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'co_n',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CoS',
            fields=[
                ('w1_id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('w2_id', models.PositiveIntegerField()),
                ('freq', models.PositiveIntegerField(blank=True, null=True)),
                ('sig', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'co_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvSo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_id', models.PositiveIntegerField()),
                ('s_id', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inv_so',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='InvW',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.PositiveIntegerField()),
                ('s_id', models.PositiveIntegerField()),
                ('pos', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'inv_w',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('sentence', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sentences',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sources',
            fields=[
                ('so_id', models.AutoField(primary_key=True, serialize=False)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sources',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('w_id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(blank=True, max_length=255, null=True)),
                ('word_ci', models.CharField(blank=True, max_length=255, null=True)),
                ('freq', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'words',
                'managed': False,
            },
        ),
    ]
