# Generated by Django 3.0.2 on 2020-09-28 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trendapp', '__first__'),
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TweetNPIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('tweet_user', models.CharField(blank=True, max_length=255, null=True)),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trendapp.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='TweetNPDateIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('tweet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trendapp.Tweet')),
            ],
        ),
        migrations.CreateModel(
            name='FeedNPIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('feed_user', models.CharField(blank=True, max_length=255, null=True)),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trendapp.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='FeedNPDateIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('frequency', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trendapp.Feed')),
            ],
        ),
        migrations.CreateModel(
            name='TweetIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('bigram', models.BooleanField(default=False)),
                ('lemmatized', models.BooleanField(default=False)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trendapp.Tweet')),
            ],
            options={
                'unique_together': {('term', 'tweet', 'bigram', 'lemmatized')},
            },
        ),
        migrations.CreateModel(
            name='TweetExIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('day', models.IntegerField()),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('count', models.IntegerField()),
                ('noun', models.BooleanField(default=False)),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.TweetEx')),
            ],
            options={
                'unique_together': {('term', 'tweet', 'day', 'month', 'year')},
            },
        ),
        migrations.CreateModel(
            name='TextExIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('noun', models.BooleanField(default=False)),
                ('text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataapp.TextEx')),
            ],
            options={
                'unique_together': {('term', 'text')},
            },
        ),
    ]
