# Generated by Django 3.0.2 on 2020-09-28 16:52

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpikeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('reference', models.ManyToManyField(to='dataapp.UserEx')),
            ],
        ),
        migrations.CreateModel(
            name='SpikeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('scores', picklefield.fields.PickledObjectField(editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spikeapp.SpikeModel')),
            ],
            options={
                'unique_together': {('start', 'end', 'model')},
            },
        ),
    ]
